/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a3d42abd-195c-49d4-90f6-a464619c8b25",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_XXpybZx0Z",
    "aws_user_pools_web_client_id": "lngbtt27utj5uo1blhr6kf0i0",
    "oauth": {}
};


export default awsmobile;
