name: ram CI/CD

on:
  push:
    branches:
      - main
#       - dev
  pull_request:
    branches:
#       - dev
      - main

jobs:

  staging:
    
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Echo branch name
      run: echo "This is Dev branch"
